# Generated by Django 6.0.6 on 2026-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.FloatField(help_text='Modul m in mm')),
                ('tooth_count', models.IntegerField(help_text='Zähnezahl z')),
                ('material', models.CharField(choices=[('16MnCr5', '16MnCr5'), ('42CrMo4', '42CrMo4'), ('C45', 'C45'), ('GG25', 'Grauguss GG25')], default='16MnCr5', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
