# Generated by Django 6.0.6 on 2026-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gears', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='tooth_count_driven',
            field=models.IntegerField(blank=True, help_text='Zähnezahl z2 (Abtrieb)', null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='tooth_count',
            field=models.IntegerField(help_text='Zähnezahl z1 (Antrieb)'),
        ),
    ]